 <h1>20BCE020 <br>
Practical-8 IRS <br>
Implement a Traditional Recommender System using the Collaborative Filtering technique. The recommender system predicts a rating for an unknown item for a specific user. <br>
    User-User Collaborative Filtering

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict={"User":["U1","U2","U3","U4","U5"],
 "movie1":[3,np.nan,5,1,5],
 "movie2":[5,4,1,np.nan,5],
 "movie3":[np.nan,5,4,2,4],
 "movie4":[2,1,2,2,np.nan],
 "movie5":[np.nan,2,np.nan,5,np.nan],
"movie6":[2,np.nan,3,np.nan,4],
"movie7":[np.nan,5,3,np.nan,2],
"movie8":[3,4,np.nan,2,5],
"movie9":[np.nan,3,1,np.nan,5],
"movie10":[3.5,5,2,np.nan,np.nan]}

In [3]:
print(dict)

{'User': ['U1', 'U2', 'U3', 'U4', 'U5'], 'movie1': [3, nan, 5, 1, 5], 'movie2': [5, 4, 1, nan, 5], 'movie3': [nan, 5, 4, 2, 4], 'movie4': [2, 1, 2, 2, nan], 'movie5': [nan, 2, nan, 5, nan], 'movie6': [2, nan, 3, nan, 4], 'movie7': [nan, 5, 3, nan, 2], 'movie8': [3, 4, nan, 2, 5], 'movie9': [nan, 3, 1, nan, 5], 'movie10': [3.5, 5, 2, nan, nan]}


In [4]:
df=pd.DataFrame(dict)

In [5]:
df=df.set_index('User')

In [6]:
print(df)

      movie1  movie2  movie3  movie4  movie5  movie6  movie7  movie8  movie9  \
User                                                                           
U1       3.0     5.0     NaN     2.0     NaN     2.0     NaN     3.0     NaN   
U2       NaN     4.0     5.0     1.0     2.0     NaN     5.0     4.0     3.0   
U3       5.0     1.0     4.0     2.0     NaN     3.0     3.0     NaN     1.0   
U4       1.0     NaN     2.0     2.0     5.0     NaN     NaN     2.0     NaN   
U5       5.0     5.0     4.0     NaN     NaN     4.0     2.0     5.0     5.0   

      movie10  
User           
U1        3.5  
U2        5.0  
U3        2.0  
U4        NaN  
U5        NaN  


In [7]:
row_mean=df.mean(axis=1)

In [8]:
print(row_mean)

User
U1    3.083333
U2    3.625000
U3    2.625000
U4    2.400000
U5    4.285714
dtype: float64


In [9]:
print(df)

      movie1  movie2  movie3  movie4  movie5  movie6  movie7  movie8  movie9  \
User                                                                           
U1       3.0     5.0     NaN     2.0     NaN     2.0     NaN     3.0     NaN   
U2       NaN     4.0     5.0     1.0     2.0     NaN     5.0     4.0     3.0   
U3       5.0     1.0     4.0     2.0     NaN     3.0     3.0     NaN     1.0   
U4       1.0     NaN     2.0     2.0     5.0     NaN     NaN     2.0     NaN   
U5       5.0     5.0     4.0     NaN     NaN     4.0     2.0     5.0     5.0   

      movie10  
User           
U1        3.5  
U2        5.0  
U3        2.0  
U4        NaN  
U5        NaN  


In [10]:
ddf = df.sub(row_mean, axis=0)

In [11]:
df=df.fillna(0)
print(df)

      movie1  movie2  movie3  movie4  movie5  movie6  movie7  movie8  movie9  \
User                                                                           
U1       3.0     5.0     0.0     2.0     0.0     2.0     0.0     3.0     0.0   
U2       0.0     4.0     5.0     1.0     2.0     0.0     5.0     4.0     3.0   
U3       5.0     1.0     4.0     2.0     0.0     3.0     3.0     0.0     1.0   
U4       1.0     0.0     2.0     2.0     5.0     0.0     0.0     2.0     0.0   
U5       5.0     5.0     4.0     0.0     0.0     4.0     2.0     5.0     5.0   

      movie10  
User           
U1        3.5  
U2        5.0  
U3        2.0  
U4        0.0  
U5        0.0  


In [12]:
print(ddf)

        movie1    movie2    movie3    movie4  movie5    movie6    movie7  \
User                                                                       
U1   -0.083333  1.916667       NaN -1.083333     NaN -1.083333       NaN   
U2         NaN  0.375000  1.375000 -2.625000  -1.625       NaN  1.375000   
U3    2.375000 -1.625000  1.375000 -0.625000     NaN  0.375000  0.375000   
U4   -1.400000       NaN -0.400000 -0.400000   2.600       NaN       NaN   
U5    0.714286  0.714286 -0.285714       NaN     NaN -0.285714 -2.285714   

        movie8    movie9   movie10  
User                                
U1   -0.083333       NaN  0.416667  
U2    0.375000 -0.625000  1.375000  
U3         NaN -1.625000 -0.625000  
U4   -0.400000       NaN       NaN  
U5    0.714286  0.714286       NaN  


In [13]:
ddf=ddf.fillna(0)

In [14]:
print(ddf)

        movie1    movie2    movie3    movie4  movie5    movie6    movie7  \
User                                                                       
U1   -0.083333  1.916667  0.000000 -1.083333   0.000 -1.083333  0.000000   
U2    0.000000  0.375000  1.375000 -2.625000  -1.625  0.000000  1.375000   
U3    2.375000 -1.625000  1.375000 -0.625000   0.000  0.375000  0.375000   
U4   -1.400000  0.000000 -0.400000 -0.400000   2.600  0.000000  0.000000   
U5    0.714286  0.714286 -0.285714  0.000000   0.000 -0.285714 -2.285714   

        movie8    movie9   movie10  
User                                
U1   -0.083333  0.000000  0.416667  
U2    0.375000 -0.625000  1.375000  
U3    0.000000 -1.625000 -0.625000  
U4   -0.400000  0.000000  0.000000  
U5    0.714286  0.714286  0.000000  


In [15]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim=cosine_similarity(ddf)

In [16]:
print(cos_sim)

[[ 1.          0.41340965 -0.35578204  0.07718544  0.22964228]
 [ 0.41340965  1.          0.24214444 -0.32064238 -0.31736554]
 [-0.35578204  0.24214444  1.         -0.32084672 -0.19523865]
 [ 0.07718544 -0.32064238 -0.32084672  1.         -0.1416998 ]
 [ 0.22964228 -0.31736554 -0.19523865 -0.1416998   1.        ]]


In [17]:
nu=int(input("Input the Number of User(1-5):"))
win=int(input("Window Size:"))
k=int(input("Top K elements:"))

Input the Number of User(1-5):1
Window Size:3
Top K elements:2


In [18]:
arr=cos_sim[nu-1].copy()

In [19]:
print(arr)

[ 1.          0.41340965 -0.35578204  0.07718544  0.22964228]


In [20]:
arr=sorted(arr,reverse=True)
print(arr)

[1.0, 0.4134096486108129, 0.22964227700182316, 0.07718543692926588, -0.3557820391516031]


In [22]:
top_k=cos_sim[nu-1]
print(top_k)
inx=[arr.index(x) for x in top_k]

[ 1.          0.41340965 -0.35578204  0.07718544  0.22964228]


In [23]:
print(inx)

[0, 1, 4, 3, 2]


In [24]:
inx_org=inx[1:win+1]
print(inx_org)

[1, 4, 3]


In [25]:
zc=ddf.columns[ddf.iloc[nu-1]==0]

In [26]:
print(zc)

Index(['movie3', 'movie5', 'movie7', 'movie9'], dtype='object')


In [55]:
print(df.iloc[1][zc[0]])
print(cos_sim[nu-1][inx_org[1]])

5.0
0.25197631533948456


In [27]:
pred_rating=[]
for i in range(len(zc)):
    col=zc[i]
    simi=0
    num=0
    den=0
    for j in range(len(inx_org)):
        num+= (cos_sim[nu-1][inx_org[j]])*(df.iloc[inx_org[j]][col])
        den+=cos_sim[nu-1][inx_org[j]]
    simi=num/den
    pred_rating.append(simi)

In [28]:
print(pred_rating)

[4.359657507683393, 1.6838150100792637, 3.5076391873668364, 3.316184989920735]


In [29]:
pred={}
for i in range(len(zc)):
    pred[zc[i]]=pred_rating[i]
print(pred)

{'movie3': 4.359657507683393, 'movie5': 1.6838150100792637, 'movie7': 3.5076391873668364, 'movie9': 3.316184989920735}


In [30]:
pr = (sorted(pred.items(), key=lambda x: x[1], reverse=True))

In [31]:
print(pr)

[('movie3', 4.359657507683393), ('movie7', 3.5076391873668364), ('movie9', 3.316184989920735), ('movie5', 1.6838150100792637)]


In [32]:
print("Recommended Movie for User",nu," are:")
for i in range(k+1):
    print(pr[i][0]," with rating =>",pr[i][1])

Recommended Movie for User 1  are:
movie3  with rating => 4.359657507683393
movie7  with rating => 3.5076391873668364
movie9  with rating => 3.316184989920735


In [33]:
print(df)

      movie1  movie2  movie3  movie4  movie5  movie6  movie7  movie8  movie9  \
User                                                                           
U1       3.0     5.0     0.0     2.0     0.0     2.0     0.0     3.0     0.0   
U2       0.0     4.0     5.0     1.0     2.0     0.0     5.0     4.0     3.0   
U3       5.0     1.0     4.0     2.0     0.0     3.0     3.0     0.0     1.0   
U4       1.0     0.0     2.0     2.0     5.0     0.0     0.0     2.0     0.0   
U5       5.0     5.0     4.0     0.0     0.0     4.0     2.0     5.0     5.0   

      movie10  
User           
U1        3.5  
U2        5.0  
U3        2.0  
U4        0.0  
U5        0.0  


In [34]:
for i in range(len(pred_rating)):
    df.iloc[nu-1][zc[i]]=pred_rating[i]

In [35]:
print(df)

      movie1  movie2    movie3  movie4    movie5  movie6    movie7  movie8  \
User                                                                         
U1       3.0     5.0  4.359658     2.0  1.683815     2.0  3.507639     3.0   
U2       0.0     4.0  5.000000     1.0  2.000000     0.0  5.000000     4.0   
U3       5.0     1.0  4.000000     2.0  0.000000     3.0  3.000000     0.0   
U4       1.0     0.0  2.000000     2.0  5.000000     0.0  0.000000     2.0   
U5       5.0     5.0  4.000000     0.0  0.000000     4.0  2.000000     5.0   

        movie9  movie10  
User                     
U1    3.316185      3.5  
U2    3.000000      5.0  
U3    1.000000      2.0  
U4    0.000000      0.0  
U5    5.000000      0.0  
