 <h1>20BCE020 <br>
Practical-9 IRS <br>
Implement a Traditional Recommender System using the Collaborative Filtering technique. The recommender system predicts a rating for an unknown item for a specific user. <br>


In [1]:
import numpy as np
import pandas as pd
dic={"User":["U1","U2","U3","U4","U5"],
 "movie1":[3,np.nan,5,1,5],
 "movie2":[5,4,1,np.nan,5],
 "movie3":[np.nan,5,4,2,4],
 "movie4":[2,1,2,2,np.nan],
 "movie5":[np.nan,2,np.nan,5,np.nan],
}
print(dic)
df=pd.DataFrame(dic)
df=df.set_index('User')

{'User': ['U1', 'U2', 'U3', 'U4', 'U5'], 'movie1': [3, nan, 5, 1, 5], 'movie2': [5, 4, 1, nan, 5], 'movie3': [nan, 5, 4, 2, 4], 'movie4': [2, 1, 2, 2, nan], 'movie5': [nan, 2, nan, 5, nan]}


In [2]:
print(df)

      movie1  movie2  movie3  movie4  movie5
User                                        
U1       3.0     5.0     NaN     2.0     NaN
U2       NaN     4.0     5.0     1.0     2.0
U3       5.0     1.0     4.0     2.0     NaN
U4       1.0     NaN     2.0     2.0     5.0
U5       5.0     5.0     4.0     NaN     NaN


In [3]:
ddf=df

In [5]:
df=df.fillna(0)
print(df)

      movie1  movie2  movie3  movie4  movie5
User                                        
U1       3.0     5.0     0.0     2.0     0.0
U2       0.0     4.0     5.0     1.0     2.0
U3       5.0     1.0     4.0     2.0     0.0
U4       1.0     0.0     2.0     2.0     5.0
U5       5.0     5.0     4.0     0.0     0.0


In [6]:
row_mean=ddf.mean(axis=1)
print(row_mean)
ddf = ddf.sub(row_mean, axis=0)

User
U1    3.333333
U2    3.000000
U3    3.000000
U4    2.500000
U5    4.666667
dtype: float64


In [7]:
ddf=ddf.fillna(0)
print(ddf)

        movie1    movie2    movie3    movie4  movie5
User                                                
U1   -0.333333  1.666667  0.000000 -1.333333     0.0
U2    0.000000  1.000000  2.000000 -2.000000    -1.0
U3    2.000000 -2.000000  1.000000 -1.000000     0.0
U4   -1.500000  0.000000 -0.500000 -0.500000     2.5
U5    0.333333  0.333333 -0.666667  0.000000     0.0


In [8]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim=cosine_similarity(ddf)
print(cos_sim)

[[ 1.          0.63433505 -0.39036003  0.18002057  0.25197632]
 [ 0.63433505  1.          0.2        -0.26352314 -0.38729833]
 [-0.39036003  0.2         1.         -0.31622777 -0.25819889]
 [ 0.18002057 -0.26352314 -0.31622777  1.         -0.06804138]
 [ 0.25197632 -0.38729833 -0.25819889 -0.06804138  1.        ]]


In [9]:
win=int(input("Window Size:"))

Window Size:3


In [10]:
pred={}
for i in range(df.shape[0]):
    k=cos_sim[i]
    a=cos_sim[i].copy()
    a=sorted(a,reverse=True)
    inx=[a.index(x) for x in k]
    inx=inx[1:win+1]
    print(inx)
    zc=ddf.columns[ddf.iloc[i]==0]
    p={}
    for j in range(len(zc)):
        col=zc[j]
        s=0
        n=0
        d=0
        for k in range(len(inx)):
            n+=(cos_sim[i][inx[k]])*(df.iloc[inx[k]][col])
            d+=cos_sim[i][inx[k]]
        s=n/d
        p[col]=s
    pred[i]=p

[1, 4, 3]
[0, 2, 3]
[1, 0, 3]
[3, 4, 0]
[4, 3, 2]


In [11]:
print(pred)

{0: {'movie3': 4.257231250236764, 'movie5': 2.0338629022645964}, 1: {'movie1': 4.624083628890043}, 2: {'movie5': 2.331558006893195}, 3: {'movie2': 0.5035129879020519}, 4: {'movie4': -0.9684172493157471, 'movie5': -0.5049380280902468}}


In [32]:
# print(len(pred[0]))
for i in range(len(pred)):
    zc=ddf.columns[ddf.iloc[i]==0]
    for k,v in pred[i].items():
        df.iloc[i][k]=v

In [33]:
print(df)

        movie1    movie2    movie3    movie4    movie5
User                                                  
U1    3.000000  5.000000  4.257231  2.000000  2.033863
U2    4.624084  4.000000  5.000000  1.000000  2.000000
U3    5.000000  1.000000  4.000000  2.000000  2.331558
U4    1.000000  0.503513  2.000000  2.000000  5.000000
U5    5.000000  5.000000  4.000000 -0.968417 -0.504938


In [73]:
import numpy as np
import pandas as pd
dic={"User":["U1","U2","U3","U4","U5"],
 "movie1":[3,np.nan,5,1,5],
 "movie2":[np.nan,4,1,np.nan,np.nan],
 "movie3":[np.nan,np.nan,4,2,4],
 "movie4":[2,np.nan,2,np.nan,np.nan],
 "movie5":[np.nan,2,np.nan,5,np.nan],
}
print(dic)
df1=pd.DataFrame(dic)
df1=df1.set_index('User')

{'User': ['U1', 'U2', 'U3', 'U4', 'U5'], 'movie1': [3, nan, 5, 1, 5], 'movie2': [nan, 4, 1, nan, nan], 'movie3': [nan, nan, 4, 2, 4], 'movie4': [2, nan, 2, nan, nan], 'movie5': [nan, 2, nan, 5, nan]}


In [74]:
print(df1)

      movie1  movie2  movie3  movie4  movie5
User                                        
U1       3.0     NaN     NaN     2.0     NaN
U2       NaN     4.0     NaN     NaN     2.0
U3       5.0     1.0     4.0     2.0     NaN
U4       1.0     NaN     2.0     NaN     5.0
U5       5.0     NaN     4.0     NaN     NaN


In [75]:
ddf1=df1.copy()

In [76]:
df1=df1.fillna(0)
print(df1)

      movie1  movie2  movie3  movie4  movie5
User                                        
U1       3.0     0.0     0.0     2.0     0.0
U2       0.0     4.0     0.0     0.0     2.0
U3       5.0     1.0     4.0     2.0     0.0
U4       1.0     0.0     2.0     0.0     5.0
U5       5.0     0.0     4.0     0.0     0.0


In [77]:
row_mean=ddf1.mean(axis=1)
print(row_mean)
ddf1= ddf1.sub(row_mean, axis=0)

User
U1    2.500000
U2    3.000000
U3    3.000000
U4    2.666667
U5    4.500000
dtype: float64


In [78]:
ddf1=ddf1.fillna(0)
print(ddf1)

        movie1  movie2    movie3  movie4    movie5
User                                              
U1    0.500000     0.0  0.000000    -0.5  0.000000
U2    0.000000     1.0  0.000000     0.0 -1.000000
U3    2.000000    -2.0  1.000000    -1.0  0.000000
U4   -1.666667     0.0 -0.666667     0.0  2.333333
U5    0.500000     0.0 -0.500000     0.0  0.000000


In [79]:
from sklearn.metrics.pairwise import cosine_similarity
cos=cosine_similarity(ddf1)
print(cos)

[[ 1.          0.          0.67082039 -0.40032038  0.5       ]
 [ 0.          1.         -0.4472136  -0.56044854  0.        ]
 [ 0.67082039 -0.4472136   1.         -0.42966892  0.2236068 ]
 [-0.40032038 -0.56044854 -0.42966892  1.         -0.24019223]
 [ 0.5         0.          0.2236068  -0.24019223  1.        ]]


In [80]:
w=int(input("Window Size:"))

Window Size:3


In [81]:
pr={}
for i in range(df.shape[0]):
    k=cos[i]
    a=cos[i].copy()
    a=sorted(a,reverse=True)
    inx=[a.index(x) for x in k]
    inx=inx[1:win+1]
    print(inx)
    zc=ddf1.columns[ddf1.iloc[i]==0]
    p={}
    for j in range(len(zc)):
        col=zc[j]
        s=0
        n=0
        d=0
        for k in range(len(inx)):
            n+=(cos[i][inx[k]])*(df1.iloc[inx[k]][col])
            d+=cos[i][inx[k]]
        s=n/d
        p[col]=s
    pr[i]=p

[3, 1, 4]
[0, 3, 4]
[4, 0, 3]
[4, 3, 0]
[3, 2, 4]


In [82]:
print(pr)

{0: {'movie2': 0.0, 'movie3': 12.032141427427428, 'movie5': -20.080353568568565}, 1: {'movie1': 1.0, 'movie3': 2.0, 'movie4': -0.0}, 2: {'movie5': -4.6224989991991965}, 3: {'movie2': 0.0, 'movie4': -2.227173477912695}, 4: {'movie2': 0.22737795965589958, 'movie4': 0.45475591931179915, 'movie5': -1.221215542037458}}


In [85]:
for i in range(len(pr)):
    zc=ddf1.columns[ddf1.iloc[i]==0]
    for k,v in pr[i].items():
        df1.iloc[i][k]=v

In [86]:
print(df1)

      movie1    movie2     movie3    movie4     movie5
User                                                  
U1       3.0  0.000000  12.032141  2.000000 -20.080354
U2       1.0  4.000000   2.000000 -0.000000   2.000000
U3       5.0  1.000000   4.000000  2.000000  -4.622499
U4       1.0  0.000000   2.000000 -2.227173   5.000000
U5       5.0  0.227378   4.000000  0.454756  -1.221216


In [89]:
print(df)

        movie1    movie2    movie3    movie4    movie5
User                                                  
U1    3.000000  5.000000  4.257231  2.000000  2.033863
U2    4.624084  4.000000  5.000000  1.000000  2.000000
U3    5.000000  1.000000  4.000000  2.000000  2.331558
U4    1.000000  0.503513  2.000000  2.000000  5.000000
U5    5.000000  5.000000  4.000000 -0.968417 -0.504938


In [88]:
difff=df-df1
difff

movie1    movie2   movie3    movie4     movie5
User                                                  
U1    0.000000  5.000000 -7.77491  0.000000  22.114216
U2    3.624084  0.000000  3.00000  1.000000   0.000000
U3    0.000000  0.000000  0.00000  0.000000   6.954057
U4    0.000000  0.503513  0.00000  4.227173   0.000000
U5    0.000000  4.772622  0.00000 -1.423173   0.716278

In [90]:
sq= np.square(difff)
ms = np.mean(sq)
rms = np.sqrt(ms)
print(rms)

movie1     1.620739
movie2     3.099401
movie3     3.726908
movie4     2.044232
movie5    10.372179
dtype: float64


D:\python\lib\site-packages\numpy\core\fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
