Implement a Traditional Recommender System using the Collaborative Filtering technique. The recommender system predicts a rating for an unknown item for a specific user.

In [1]:
import numpy as np
import pandas as pd

USER-USER COLLABORATIVE FILTERING

In [39]:
data={'item1':[3,5,np.nan,2,np.nan],'item2':[np.nan,4,5,1,2],'item3':[5,1,4,2,np.nan],'item4':[1,np.nan,2,2,5],'item5':[5,5,4,np.nan,np.nan],'item6':[2,3,np.nan,5,np.nan]}
df=pd.DataFrame(data,index=['user1','user2','user3','user4','user5'])
df


item1  item2  item3  item4  item5  item6
user1    3.0    NaN    5.0    1.0    5.0    2.0
user2    5.0    4.0    1.0    NaN    5.0    3.0
user3    NaN    5.0    4.0    2.0    4.0    NaN
user4    2.0    1.0    2.0    2.0    NaN    5.0
user5    NaN    2.0    NaN    5.0    NaN    NaN

In [40]:
rowmeans=(np.nanmean(df,axis=1,keepdims=True))
print(rowmeans)

[[3.2 ]
 [3.6 ]
 [3.75]
 [2.4 ]
 [3.5 ]]


In [41]:
df=np.array(df)
print(df)


[[ 3. nan  5.  1.  5.  2.]
 [ 5.  4.  1. nan  5.  3.]
 [nan  5.  4.  2.  4. nan]
 [ 2.  1.  2.  2. nan  5.]
 [nan  2. nan  5. nan nan]]


In [42]:
df=df-rowmeans
print(df)

[[-0.2    nan  1.8  -2.2   1.8  -1.2 ]
 [ 1.4   0.4  -2.6    nan  1.4  -0.6 ]
 [  nan  1.25  0.25 -1.75  0.25   nan]
 [-0.4  -1.4  -0.4  -0.4    nan  2.6 ]
 [  nan -1.5    nan  1.5    nan   nan]]


In [43]:
df=pd.DataFrame(df,index=['user1','user2','user3','user4','user5'],columns=['item1','item2','item3','item4','item5','item6'])
df

item1  item2  item3  item4  item5  item6
user1   -0.2    NaN   1.80  -2.20   1.80   -1.2
user2    1.4   0.40  -2.60    NaN   1.40   -0.6
user3    NaN   1.25   0.25  -1.75   0.25    NaN
user4   -0.4  -1.40  -0.40  -0.40    NaN    2.6
user5    NaN  -1.50    NaN   1.50    NaN    NaN

In [44]:
df=df.replace(np.nan,0)
df

item1  item2  item3  item4  item5  item6
user1   -0.2   0.00   1.80  -2.20   1.80   -1.2
user2    1.4   0.40  -2.60   0.00   1.40   -0.6
user3    0.0   1.25   0.25  -1.75   0.25    0.0
user4   -0.4  -1.40  -0.40  -0.40   0.00    2.6
user5    0.0  -1.50   0.00   1.50   0.00    0.0

In [45]:
data=np.array(df)
data

array([[-0.2 ,  0.  ,  1.8 , -2.2 ,  1.8 , -1.2 ],
       [ 1.4 ,  0.4 , -2.6 ,  0.  ,  1.4 , -0.6 ],
       [ 0.  ,  1.25,  0.25, -1.75,  0.25,  0.  ],
       [-0.4 , -1.4 , -0.4 , -0.4 ,  0.  ,  2.6 ],
       [ 0.  , -1.5 ,  0.  ,  1.5 ,  0.  ,  0.  ]])

In [46]:
u=input("PLEASE ENTER THE USER FOR WHOM TO PREDICT RATINGS: ")
u=u.split("user")
u=int(u[1])-1
print(u)

PLEASE ENTER THE USER FOR WHOM TO PREDICT RATINGS: user5
4


In [47]:
ldata=list(data)
ldata

[array([-0.2,  0. ,  1.8, -2.2,  1.8, -1.2]),
 array([ 1.4,  0.4, -2.6,  0. ,  1.4, -0.6]),
 array([ 0.  ,  1.25,  0.25, -1.75,  0.25,  0.  ]),
 array([-0.4, -1.4, -0.4, -0.4,  0. ,  2.6]),
 array([ 0. , -1.5,  0. ,  1.5,  0. ,  0. ])]

In [48]:
userdata=np.array(ldata.pop(u))
userdata

array([ 0. , -1.5,  0. ,  1.5,  0. ,  0. ])

In [49]:
data=np.array(ldata)
data

array([[-0.2 ,  0.  ,  1.8 , -2.2 ,  1.8 , -1.2 ],
       [ 1.4 ,  0.4 , -2.6 ,  0.  ,  1.4 , -0.6 ],
       [ 0.  ,  1.25,  0.25, -1.75,  0.25,  0.  ],
       [-0.4 , -1.4 , -0.4 , -0.4 ,  0.  ,  2.6 ]])

In [50]:
from numpy.linalg import norm

def cosine(a,b):
    cos=np.dot(a,b)/(norm(a)*norm(b))
    return cos

In [51]:
simi=[]
idx=[]
m=0
for j in data:
    s=cosine(userdata,j)
    simi.append(s)
    idx.append(m)
    m+=1
print(simi)
print(idx)

[-0.4348131782731522, -0.08451542547285165, -0.9733285267845753, 0.2331262020600784]
[0, 1, 2, 3]


In [65]:
m

2

In [52]:
for j in range(len(simi)):
    for m in range(len(simi)-1):
        if simi[m]<=simi[j]:
            t=simi[m]
            simi[m]=simi[j]
            simi[j]=t
            
            t=idx[m]
            idx[m]=idx[j]
            idx[j]=t
print(simi)
print(idx)
            
            
            

[0.2331262020600784, -0.08451542547285165, -0.4348131782731522, -0.9733285267845753]
[3, 1, 0, 2]


In [53]:
n=int(input('ENTER THE VALUE OF N: '))
n

ENTER THE VALUE OF N: 3


3

In [54]:
idx=idx[:n]
print(idx)

[3, 1, 0]


In [55]:
simi=simi[:n]
print(simi)

[0.2331262020600784, -0.08451542547285165, -0.4348131782731522]


In [56]:
predata=data[idx]
print('DATA:')
print(predata)
print('USERDATA')
print(userdata)

DATA:
[[-0.4 -1.4 -0.4 -0.4  0.   2.6]
 [ 1.4  0.4 -2.6  0.   1.4 -0.6]
 [-0.2  0.   1.8 -2.2  1.8 -1.2]]
USERDATA
[ 0.  -1.5  0.   1.5  0.   0. ]


In [57]:
predindex=[]
simi

[0.2331262020600784, -0.08451542547285165, -0.4348131782731522]

In [58]:
for j in range(len(userdata)):
    if userdata[j]==0:
        predindex.append(j)
        num=0
        den=0
        for k in range(len(predata)):
            num=num+simi[k]*predata[k][j]
            den=den+simi[k]
        userdata[j]=num/den
userdata
            
            


array([ 0.43538922, -1.5       ,  2.29269248,  1.5       ,  3.14807043,
       -4.11811078])

In [59]:
predindex

[0, 2, 4, 5]

In [61]:
p=userdata[predindex]

In [62]:
p

array([ 0.43538922,  2.29269248,  3.14807043, -4.11811078])

In [64]:
k=int(input('Enter the value of K for recommendation: '))

Enter the value of K for recommendation: 3


In [67]:
idx1=predindex

In [68]:
for j in range(len(p)):
    for m in range(len(p)-1):
        if p[m]<=p[j]:
            t=p[m]
            p[m]=p[j]
            p[j]=t
            
            t=idx1[m]
            idx1[m]=idx1[j]
            idx1[j]=t
print(p)
print(idx1)
            
            
            

[ 3.14807043  2.29269248  0.43538922 -4.11811078]
[4, 2, 0, 5]


In [71]:
for m in range(k):
    print("The movie recommended: ",str(idx1[m]+1))
    

The movie recommended:  5
The movie recommended:  3
The movie recommended:  1


ITEM-ITEM COLLABORATIVE FILTERING

In [72]:
df

item1  item2  item3  item4  item5  item6
user1   -0.2   0.00   1.80  -2.20   1.80   -1.2
user2    1.4   0.40  -2.60   0.00   1.40   -0.6
user3    0.0   1.25   0.25  -1.75   0.25    0.0
user4   -0.4  -1.40  -0.40  -0.40   0.00    2.6
user5    0.0  -1.50   0.00   1.50   0.00    0.0

In [73]:
n=np.array(df)
n

array([[-0.2 ,  0.  ,  1.8 , -2.2 ,  1.8 , -1.2 ],
       [ 1.4 ,  0.4 , -2.6 ,  0.  ,  1.4 , -0.6 ],
       [ 0.  ,  1.25,  0.25, -1.75,  0.25,  0.  ],
       [-0.4 , -1.4 , -0.4 , -0.4 ,  0.  ,  2.6 ],
       [ 0.  , -1.5 ,  0.  ,  1.5 ,  0.  ,  0.  ]])

In [74]:
n=n.T
n

array([[-0.2 ,  1.4 ,  0.  , -0.4 ,  0.  ],
       [ 0.  ,  0.4 ,  1.25, -1.4 , -1.5 ],
       [ 1.8 , -2.6 ,  0.25, -0.4 ,  0.  ],
       [-2.2 ,  0.  , -1.75, -0.4 ,  1.5 ],
       [ 1.8 ,  1.4 ,  0.25,  0.  ,  0.  ],
       [-1.2 , -0.6 ,  0.  ,  2.6 ,  0.  ]])

In [81]:
data={'item1':[3,5,np.nan,2,np.nan],'item2':[np.nan,4,5,1,2],'item3':[5,1,4,2,np.nan],'item4':[1,np.nan,2,2,5],'item5':[5,5,4,np.nan,np.nan],'item6':[2,3,np.nan,5,np.nan]}
df1=pd.DataFrame(data,index=['user1','user2','user3','user4','user5'])


In [82]:
df1

item1  item2  item3  item4  item5  item6
user1    3.0    NaN    5.0    1.0    5.0    2.0
user2    5.0    4.0    1.0    NaN    5.0    3.0
user3    NaN    5.0    4.0    2.0    4.0    NaN
user4    2.0    1.0    2.0    2.0    NaN    5.0
user5    NaN    2.0    NaN    5.0    NaN    NaN

In [83]:
n=np.array(df1)
n

array([[ 3., nan,  5.,  1.,  5.,  2.],
       [ 5.,  4.,  1., nan,  5.,  3.],
       [nan,  5.,  4.,  2.,  4., nan],
       [ 2.,  1.,  2.,  2., nan,  5.],
       [nan,  2., nan,  5., nan, nan]])

In [84]:
n=n.T

In [85]:
n

array([[ 3.,  5., nan,  2., nan],
       [nan,  4.,  5.,  1.,  2.],
       [ 5.,  1.,  4.,  2., nan],
       [ 1., nan,  2.,  2.,  5.],
       [ 5.,  5.,  4., nan, nan],
       [ 2.,  3., nan,  5., nan]])

In [86]:
df1=pd.DataFrame(n,index=['movie1','movie2','movie3','movie4','movie5','movie6'],columns=['user1','user2','user3','user4','user5'])
df1

user1  user2  user3  user4  user5
movie1    3.0    5.0    NaN    2.0    NaN
movie2    NaN    4.0    5.0    1.0    2.0
movie3    5.0    1.0    4.0    2.0    NaN
movie4    1.0    NaN    2.0    2.0    5.0
movie5    5.0    5.0    4.0    NaN    NaN
movie6    2.0    3.0    NaN    5.0    NaN

In [87]:
rowmeans=(np.nanmean(df1,axis=1,keepdims=True))
print(rowmeans)

[[3.33333333]
 [3.        ]
 [3.        ]
 [2.5       ]
 [4.66666667]
 [3.33333333]]


In [88]:
n

array([[ 3.,  5., nan,  2., nan],
       [nan,  4.,  5.,  1.,  2.],
       [ 5.,  1.,  4.,  2., nan],
       [ 1., nan,  2.,  2.,  5.],
       [ 5.,  5.,  4., nan, nan],
       [ 2.,  3., nan,  5., nan]])

In [89]:
n=n-rowmeans

In [90]:
n

array([[-0.33333333,  1.66666667,         nan, -1.33333333,         nan],
       [        nan,  1.        ,  2.        , -2.        , -1.        ],
       [ 2.        , -2.        ,  1.        , -1.        ,         nan],
       [-1.5       ,         nan, -0.5       , -0.5       ,  2.5       ],
       [ 0.33333333,  0.33333333, -0.66666667,         nan,         nan],
       [-1.33333333, -0.33333333,         nan,  1.66666667,         nan]])

In [91]:
df1=pd.DataFrame(n,index=['movie1','movie2','movie3','movie4','movie5','movie6'],columns=['user1','user2','user3','user4','user5'])
df1

user1     user2     user3     user4  user5
movie1 -0.333333  1.666667       NaN -1.333333    NaN
movie2       NaN  1.000000  2.000000 -2.000000   -1.0
movie3  2.000000 -2.000000  1.000000 -1.000000    NaN
movie4 -1.500000       NaN -0.500000 -0.500000    2.5
movie5  0.333333  0.333333 -0.666667       NaN    NaN
movie6 -1.333333 -0.333333       NaN  1.666667    NaN

In [94]:
df1=df1.replace(np.nan,0)
df1

user1     user2     user3     user4  user5
movie1 -0.333333  1.666667  0.000000 -1.333333    0.0
movie2  0.000000  1.000000  2.000000 -2.000000   -1.0
movie3  2.000000 -2.000000  1.000000 -1.000000    0.0
movie4 -1.500000  0.000000 -0.500000 -0.500000    2.5
movie5  0.333333  0.333333 -0.666667  0.000000    0.0
movie6 -1.333333 -0.333333  0.000000  1.666667    0.0

In [96]:
data=np.array(df1)
data

array([[-0.33333333,  1.66666667,  0.        , -1.33333333,  0.        ],
       [ 0.        ,  1.        ,  2.        , -2.        , -1.        ],
       [ 2.        , -2.        ,  1.        , -1.        ,  0.        ],
       [-1.5       ,  0.        , -0.5       , -0.5       ,  2.5       ],
       [ 0.33333333,  0.33333333, -0.66666667,  0.        ,  0.        ],
       [-1.33333333, -0.33333333,  0.        ,  1.66666667,  0.        ]])

In [98]:
u=input("PLEASE ENTER THE USER FOR WHOM TO PREDICT RATINGS: ")
u=u.split("movie")
u=int(u[1])-1
print(u)

PLEASE ENTER THE USER FOR WHOM TO PREDICT RATINGS: movie6
5


In [99]:
ldata=list(data)
ldata

[array([-0.33333333,  1.66666667,  0.        , -1.33333333,  0.        ]),
 array([ 0.,  1.,  2., -2., -1.]),
 array([ 2., -2.,  1., -1.,  0.]),
 array([-1.5,  0. , -0.5, -0.5,  2.5]),
 array([ 0.33333333,  0.33333333, -0.66666667,  0.        ,  0.        ]),
 array([-1.33333333, -0.33333333,  0.        ,  1.66666667,  0.        ])]

In [100]:
userdata=np.array(ldata.pop(u))
userdata

array([-1.33333333, -0.33333333,  0.        ,  1.66666667,  0.        ])

In [101]:
data=np.array(ldata)
data

array([[-0.33333333,  1.66666667,  0.        , -1.33333333,  0.        ],
       [ 0.        ,  1.        ,  2.        , -2.        , -1.        ],
       [ 2.        , -2.        ,  1.        , -1.        ,  0.        ],
       [-1.5       ,  0.        , -0.5       , -0.5       ,  2.5       ],
       [ 0.33333333,  0.33333333, -0.66666667,  0.        ,  0.        ]])

In [106]:
simi=[]
idx=[]
m=0
for j in data:
    s=cosine(userdata,j)
    simi.append(s)
    idx.append(m)
    m+=1
print(simi)
print(idx)

[-0.4999999999999999, -0.5367450401216932, -0.5367450401216932, 0.1800205749557739, -0.31497039417435574]
[0, 1, 2, 3, 4]


In [107]:
for j in range(len(simi)):
    for m in range(len(simi)-1):
        if simi[m]<=simi[j]:
            t=simi[m]
            simi[m]=simi[j]
            simi[j]=t
            
            t=idx[m]
            idx[m]=idx[j]
            idx[j]=t
print(simi)
print(idx)
            
            
            

[0.1800205749557739, -0.31497039417435574, -0.4999999999999999, -0.5367450401216932, -0.5367450401216932]
[3, 4, 0, 2, 1]


In [108]:
n=int(input('ENTER THE VALUE OF N: '))
n

ENTER THE VALUE OF N: 3


3

In [109]:
idx=idx[:n]
print(idx)

[3, 4, 0]


In [110]:
simi=simi[:n]
print(simi)

[0.1800205749557739, -0.31497039417435574, -0.4999999999999999]


In [111]:
predata=data[idx]
print('DATA:')
print(predata)
print('USERDATA')
print(userdata)

DATA:
[[-1.5         0.         -0.5        -0.5         2.5       ]
 [ 0.33333333  0.33333333 -0.66666667  0.          0.        ]
 [-0.33333333  1.66666667  0.         -1.33333333  0.        ]]
USERDATA
[-1.33333333 -0.33333333  0.          1.66666667  0.        ]


In [112]:
predindex=[]
simi

[0.1800205749557739, -0.31497039417435574, -0.4999999999999999]

In [113]:
for j in range(len(userdata)):
    if userdata[j]==0:
        predindex.append(j)
        num=0
        den=0
        for k in range(len(predata)):
            num=num+simi[k]*predata[k][j]
            den=den+simi[k]
        userdata[j]=num/den
userdata
            
            


array([-1.33333333, -0.33333333, -0.18894403,  1.66666667, -0.70879843])

In [114]:
p=userdata[predindex]
p

array([-0.18894403, -0.70879843])

In [115]:
k=int(input('Enter the value of K for recommendation: '))

Enter the value of K for recommendation: 2


In [116]:
idx1=predindex

In [117]:
for j in range(len(p)):
    for m in range(len(p)-1):
        if p[m]<=p[j]:
            t=p[m]
            p[m]=p[j]
            p[j]=t
            
            t=idx1[m]
            idx1[m]=idx1[j]
            idx1[j]=t
print(p)
print(idx1)
            
            
            

[-0.18894403 -0.70879843]
[2, 4]


In [119]:
for m in range(len(idx1)):
    print("User who gave rating "+str(p[m])+" : "+str(idx1[m]+1))

User who gave rating -0.18894402624235923 : 3
User who gave rating -0.7087984337774956 : 5
